# Generated by Django 5.0.2 on 2024-02-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date_payment',
            new_name='date',
        ),
    ]
